#!/bin/sh

# Based on an alias written by doener on #git.

# usage: git retrack URL BRANCH

branch=$(git rev-parse --symbolic-full-name HEAD | sed 's/refs\/heads\///')

git config branch.$branch.remote "$1"
git config branch.$branch.merge "refs/heads/${2:-$branch}"
