#!/bin/bash

# If you are using MacPorts, you'll need to install 'patchutils'

BASE=upstream

git diff $BASE HEAD > changes.diff
git diff -w $BASE HEAD > changes-w.diff

interdiff changes-w.diff changes.diff > ws.diff
rm changes.diff changes-w.diff

patch -p1 -R < ws.diff && rm ws.diff && \
    git commit -a -m "Match whitespace with $BASE"

### git-fixws ends here
