#!/usr/bin/env bash
set -e

dirs="."
if [[ "$1" == --dir ]]; then
    dirs="$2"
    shift 2
fi

exec find $dirs \( -path '*/.git/config' -o \
                   -regex '.*/.git/.*/config' \) -type f -print0 \
         | parallel -0 --bar -j0 --delay 1 -k "git --git-dir={//} $*"
