#!/bin/sh

# Copyright (c) 2008 Andrew Raines
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Pastebin -> code.
#
#    git apply-url https://gist.github.com/raw/.../...53b5
#    git apply-url http://paste.lisp.org/display/99999999/raw
#    etc.

URL=$1

function error {
  echo $*
  exit 1
}

if [[ ! $URL ]]; then
  error $0 URL
fi

if [[ -x $(which curl) && $(curl -V | grep https) ]]; then
  fetch="curl -s"
elif [[ -x $(which wget) ]]; then
  fetch="wget -O - -q --no-check-certificate"
else
  error need curl or wget
fi

$fetch $URL | patch -p1
