#!/bin/sh

# The job of git-flush is to recompactify your repository to be as small
# as possible, by dropping all reflogs, stashes, and other cruft that may
# be bloating your pack files.

rm -fr .git/refs/original
if [ -f .git/info/refs ]; then
    perl -i -ne 'print unless /refs\/original/;' .git/info/refs
fi
if [ -f .git/packed-refs ]; then
    perl -i -ne 'print unless /refs\/original/;' .git/packed-refs
fi

git reflog expire --expire=0 --all

if [ "$1" = "-f" ]; then
    git stash clear
fi

git repack -adf #--window=200 --depth=50
git prune
