#!/usr/bin/env ruby

require 'fileutils'

$name = "git merge-to-svn" 

def usage retcode=0
  puts <<USAGE
usage: #{$name} [options] <ref>
USAGE
  exit retcode
end

def die msg, usage=false
  $stderr.puts msg
  usage ? usage(-1) : exit(-1)
end

def git_dir
  $git_dir ||= %x(git rev-parse --git-dir).sub(/\n$/,'')
end

def rev_list ref
  %x(git rev-list --reverse --first-parent #{ref}).split(/\n/)
end

def patch_id hash
  id = %x(git show #{hash} | git patch-id).sub(/\n$/,'')
  id.empty? ? nil : id
end

def merge? hash
  patch_id.nil?
end

def merge_to_svn ref, opts={}
  hashes = rev_list ref
  hashes.each do |hash|
    if merge? hash
      %x(git merge -q --squash #{hash} && git commit -C #{hash})
    else
      %x(git cherry-pick #{hash})
    end
  end
end


ref  = nil
opts = {}
args = ARGV.dup
while arg = args.shift
  case arg
  when /-h|--help/
    usage
  when /^-/
    die "unknow option #{arg}", true
  else
    case
    when ref
      usage -1
    else
      ref = arg
    end
  end
end
usage -1 unless ref
merge_to_svn ref, opts
