#!/bin/bash -e

DIRS="."
if [[ "$1" == --dir ]]; then
    shift 1
    DIRS="$1"
    shift 1
fi

exec find $DIRS \( -path '*/.git/config' -o \
                   -regex '.*/.git/.*/config' \) -type f -print0 \
         | parallel -0 --bar --delay 1 -k "git --git-dir={//} $@"
