#!/bin/sh

# Pastebin -> code.
#
#    git apply-url https://gist.github.com/raw/.../...53b5
#    git apply-url http://paste.lisp.org/display/99999999/raw
#    etc.

URL=$1

function error {
  echo $*
  exit 1
}

if [[ ! $URL ]]; then
  error $0 URL
fi

if [[ -x $(which curl) && $(curl -V | grep https) ]]; then
  fetch="curl -s"
elif [[ -x $(which wget) ]]; then
  fetch="wget -O - -q --no-check-certificate"
else
  error need curl or wget
fi

$fetch $URL | patch -p1
