#!/bin/sh

if [ -f .git/objects/pack/*.pack ]; then
  mkdir /tmp/tmpgit.$$
  GIT_DIR=/tmp/tmpgit.$$ git init

  for pack in .git/objects/pack/*.pack; do
    GIT_DIR=/tmp/tmpgit.$$ git unpack-objects < $pack
  done

  rsync -a --info=PROGRESS2 --delete /tmp/tmpgit.$$/objects/ .git/objects/

  rm -fr /tmp/tmpgit.$$
else
  echo "No packs to unpack"
  exit 1
fi
