#!/bin/bash
# git release <branch>

# destination branch as parameter - depends on merge strategy, typically release
DST_BRANCH=""
if [ ! -z "$1" ]; then
    DST_BRANCH="$1"
else
	echo "Usage: git release <branch>"
	exit 1
fi

# get  current branch - typically master or develop
cb=`git rev-parse --abbrev-ref HEAD`
# push current branch, pull destination branch, fast forward merge from current branch to destination branch, push and return
git push && git checkout $DST_BRANCH && git pull && git merge --ff $cb && git push && git checkout $cb